project:
  type: website
  output-dir: docs

website:
  title: "张乐乐 | 农业工程与信息技术硕士"
  navbar:
    logo: images/profile-photo.jpg
    background: primary
    search: true
    left:
      - href: index.qmd
        text: 首页
      - href: education.qmd
        text: 教育经历
      - href: honors.qmd
        text: 获奖荣誉
      - href: contact.qmd
        text: 联系方式
  page-footer:
    center: 
      - text: "© 2025 张乐乐1. 保留所有权利。"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: article